act: null
angular_discrete_month_encoder: false
angular_hour_encoder: true
apparent_temperature: false
apply_log_scaling: false # true
average_week_rain: true
batch_size: 64
bias: false
business_days: false
condition_on_future: true
days_since_last_rain: true
dewpoint: false
discounted_accumulated_rain_volume: false
dropout: 0.04625028366987123
epochs: 70
grace_period: 35
group: dec_WaveNet_2024-01-06T02:14:17.527024
hidden_channels: 64
humidity: true
in_channels: 24
input_dropout: 0.12090457919016082
loss: mse
lr: 0.0002901306070321085
lr_decay: 0.9341769780283024
lr_patience: null
markov_probability: 0.8397830474960744
model_name: WaveNet
name: dec_model_WaveNet
normalization: quantile-0.85
num_cpus: 119
num_cpus_per_task: 2.0
num_future_conditionals: 14
num_gpus: null
num_gpus_per_task: 0.125
num_layers: 6
num_samples: 2000
one_hot_weekday_encoder: true
optimizer: adam
out_channels: 10
output_act: null
output_dropout: 0.06783849844239484
predict_week_residual: true
project: BoN Demand Forecasting
rain: false
reduction_factor: 4
seed: null
seq_seed_len: 64
seq_test_target_len: 48
seq_train_target_len: 1
seq_val_target_len: 12
skip_channels: 64
start_probability: 0.004535078290199963
storage_path: null
temperature: true
train_only: false
use_res_conv: true
val_every: 1
windspeed: true
